### ISSUE TITLE
Extending GermaNER feature extractors

### ISSUE THREAD

**Issue by ghost** [tudarmstadt-lt/GermaNER#2]
hello,

issue 1:i am exploring GermaNER Feature extractors and followed the instruction given in link:
https://github.com/tudarmstadt-lt/GermaNER/blob/master/germaner/src/main/java/de/tu/darmstadt/lt/ner/doc/Customizing-GermaNER.md#extending-germaner-feature-extractors

but the i am not able to see any changes in the output.tsv file
i added the listFileName.txt file in data.zip 

issue2:i want to use the GermaNER tool for adding new feature similar to  VornameListFeatureExtractor I want to add some MYListFeature.

I made the following changes 
1.  added my MYListFile in data.zip
2.  added new configuration in config.properties
3.  did changes in GetFeaturesFromConfigFile.java and Features2Xml.java

but still I am not able to see the changes in my output file ,could please help me how I can come up with new FeatureExtrator.

Thanks and Regards
Roopa

**Comment by ghost** [comment]
any Update on Extending GermaNER feature extractors #2

**Comment by seyyaw** [comment]
There is a new JAR file [here](https://github.com/tudarmstadt-lt/GermaNER/releases/download/germaNER0.9.1/GermaNER-train-04-12-2016.jar). Follow the instructions [here](https://github.com/tudarmstadt-lt/GermaNER/blob/master/README.md#train-germaner-with-your-own-training-file-and-feature-files) on how to modify new existing features or look-up or list features
