### ISSUE TITLE
FirstNameFeature in GermaNER

### ISSUE THREAD

**Issue by ghost** [tudarmstadt-lt/GermaNER#4]
Could  any one please Explain How this  useFirstNameFeature=1 feature works in GermaNER 
Any Examples it would be of great help.
Thanks in advance.

**Comment by seyyaw** [comment]
There is a file **vornameList.txt** in the data.zip file. It actually checks if a token is in one of this first names lists.  For how to update the **vornameList.txt** see issue #2
